name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rewards-library
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci # or yarn install
      - uses: sibiraj-s/action-eslint@v2
        working-directory: ./rewards-library
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true